// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Unshackled.Kitchen.Core.Data;

#nullable disable

namespace Unshackled.Kitchen.Core.Data.Migrations.MSSQL
{
    [DbContext(typeof(MsSqlServerDbContext))]
    partial class MsSqlServerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("uk_Roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("uk_RoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("uk_UserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("uk_UserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("uk_UserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("uk_UserTokens", (string)null);
                });

            modelBuilder.Entity("Unshackled.Kitchen.Core.Data.Entities.CookbookEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DateCreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateLastModifiedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long>("MemberId")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("DateCreatedUtc");

                    b.HasIndex("DateLastModifiedUtc");

                    b.HasIndex("MemberId");

                    b.ToTable("uk_Cookbooks", (string)null);
                });

            modelBuilder.Entity("Unshackled.Kitchen.Core.Data.Entities.CookbookInviteEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CookbookId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DateCreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateLastModifiedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Permissions")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CookbookId");

                    b.HasIndex("DateCreatedUtc");

                    b.HasIndex("DateLastModifiedUtc");

                    b.ToTable("uk_CookbookInvites", (string)null);
                });

            modelBuilder.Entity("Unshackled.Kitchen.Core.Data.Entities.CookbookMemberEntity", b =>
                {
                    b.Property<long>("CookbookId")
                        .HasColumnType("bigint");

                    b.Property<long>("MemberId")
                        .HasColumnType("bigint");

                    b.Property<int>("PermissionLevel")
                        .HasColumnType("int");

                    b.HasKey("CookbookId", "MemberId");

                    b.HasIndex("MemberId");

                    b.ToTable("uk_CookbookMembers", (string)null);
                });

            modelBuilder.Entity("Unshackled.Kitchen.Core.Data.Entities.CookbookRecipeEntity", b =>
                {
                    b.Property<long>("CookbookId")
                        .HasColumnType("bigint");

                    b.Property<long>("RecipeId")
                        .HasColumnType("bigint");

                    b.Property<long>("HouseholdId")
                        .HasColumnType("bigint");

                    b.Property<long>("MemberId")
                        .HasColumnType("bigint");

                    b.HasKey("CookbookId", "RecipeId");

                    b.HasIndex("HouseholdId");

                    b.HasIndex("MemberId");

                    b.HasIndex("RecipeId");

                    b.ToTable("uk_CookbookRecipes", (string)null);
                });

            modelBuilder.Entity("Unshackled.Kitchen.Core.Data.Entities.HouseholdEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DateCreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateLastModifiedUtc")
                        .HasColumnType("datetime2");

                    b.Property<long>("MemberId")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("DateCreatedUtc");

                    b.HasIndex("DateLastModifiedUtc");

                    b.HasIndex("MemberId");

                    b.ToTable("uk_Households", (string)null);
                });

            modelBuilder.Entity("Unshackled.Kitchen.Core.Data.Entities.HouseholdInviteEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DateCreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateLastModifiedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long>("HouseholdId")
                        .HasColumnType("bigint");

                    b.Property<int>("Permissions")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DateCreatedUtc");

                    b.HasIndex("DateLastModifiedUtc");

                    b.HasIndex("HouseholdId");

                    b.ToTable("uk_HouseholdInvites", (string)null);
                });

            modelBuilder.Entity("Unshackled.Kitchen.Core.Data.Entities.HouseholdMemberEntity", b =>
                {
                    b.Property<long>("HouseholdId")
                        .HasColumnType("bigint");

                    b.Property<long>("MemberId")
                        .HasColumnType("bigint");

                    b.Property<int>("PermissionLevel")
                        .HasColumnType("int");

                    b.HasKey("HouseholdId", "MemberId");

                    b.HasIndex("MemberId");

                    b.ToTable("uk_HouseholdMembers", (string)null);
                });

            modelBuilder.Entity("Unshackled.Kitchen.Core.Data.Entities.MealDefinitionEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DateCreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateLastModifiedUtc")
                        .HasColumnType("datetime2");

                    b.Property<long>("HouseholdId")
                        .HasColumnType("bigint");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("DateCreatedUtc");

                    b.HasIndex("DateLastModifiedUtc");

                    b.HasIndex("HouseholdId");

                    b.HasIndex("SortOrder");

                    b.HasIndex("Title");

                    b.ToTable("uk_MealDefinitions", (string)null);
                });

            modelBuilder.Entity("Unshackled.Kitchen.Core.Data.Entities.MealPlanRecipeEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DateCreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateLastModifiedUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("DatePlanned")
                        .HasColumnType("date");

                    b.Property<long>("HouseholdId")
                        .HasColumnType("bigint");

                    b.Property<long?>("MealDefinitionId")
                        .HasColumnType("bigint");

                    b.Property<long>("RecipeId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Scale")
                        .HasPrecision(4, 2)
                        .HasColumnType("decimal(4,2)");

                    b.HasKey("Id");

                    b.HasIndex("DateCreatedUtc");

                    b.HasIndex("DateLastModifiedUtc");

                    b.HasIndex("HouseholdId");

                    b.HasIndex("MealDefinitionId");

                    b.HasIndex("RecipeId");

                    b.HasIndex("DatePlanned", "MealDefinitionId");

                    b.ToTable("uk_MealPlanRecipes", (string)null);
                });

            modelBuilder.Entity("Unshackled.Kitchen.Core.Data.Entities.ProductBundleEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DateCreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateLastModifiedUtc")
                        .HasColumnType("datetime2");

                    b.Property<long>("HouseholdId")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("DateCreatedUtc");

                    b.HasIndex("DateLastModifiedUtc");

                    b.HasIndex("HouseholdId");

                    b.HasIndex("HouseholdId", "Title");

                    b.ToTable("uk_ProductBundles", (string)null);
                });

            modelBuilder.Entity("Unshackled.Kitchen.Core.Data.Entities.ProductBundleItemEntity", b =>
                {
                    b.Property<long>("ProductBundleId")
                        .HasColumnType("bigint");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("ProductBundleId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("uk_ProductBundleItems", (string)null);
                });

            modelBuilder.Entity("Unshackled.Kitchen.Core.Data.Entities.ProductCategoryEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DateCreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateLastModifiedUtc")
                        .HasColumnType("datetime2");

                    b.Property<long>("HouseholdId")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("DateCreatedUtc");

                    b.HasIndex("DateLastModifiedUtc");

                    b.HasIndex("HouseholdId");

                    b.HasIndex("Title");

                    b.ToTable("uk_ProductCategories", (string)null);
                });

            modelBuilder.Entity("Unshackled.Kitchen.Core.Data.Entities.ProductEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("AddedSugars")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<decimal>("AddedSugarsN")
                        .HasPrecision(12, 6)
                        .HasColumnType("decimal(12,6)");

                    b.Property<int>("AddedSugarsUnit")
                        .HasColumnType("int");

                    b.Property<decimal>("Biotin")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<decimal>("BiotinN")
                        .HasPrecision(12, 6)
                        .HasColumnType("decimal(12,6)");

                    b.Property<int>("BiotinUnit")
                        .HasColumnType("int");

                    b.Property<string>("Brand")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal>("Calcium")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<decimal>("CalciumN")
                        .HasPrecision(12, 6)
                        .HasColumnType("decimal(12,6)");

                    b.Property<int>("CalciumUnit")
                        .HasColumnType("int");

                    b.Property<int>("Calories")
                        .HasColumnType("int");

                    b.Property<int>("CaloriesFromFat")
                        .HasColumnType("int");

                    b.Property<decimal>("Chloride")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<decimal>("ChlorideN")
                        .HasPrecision(12, 6)
                        .HasColumnType("decimal(12,6)");

                    b.Property<int>("ChlorideUnit")
                        .HasColumnType("int");

                    b.Property<decimal>("Cholesterol")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<decimal>("CholesterolN")
                        .HasPrecision(12, 6)
                        .HasColumnType("decimal(12,6)");

                    b.Property<int>("CholesterolUnit")
                        .HasColumnType("int");

                    b.Property<decimal>("Choline")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<decimal>("CholineN")
                        .HasPrecision(12, 6)
                        .HasColumnType("decimal(12,6)");

                    b.Property<int>("CholineUnit")
                        .HasColumnType("int");

                    b.Property<decimal>("Chromium")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<decimal>("ChromiumN")
                        .HasPrecision(12, 6)
                        .HasColumnType("decimal(12,6)");

                    b.Property<int>("ChromiumUnit")
                        .HasColumnType("int");

                    b.Property<decimal>("Copper")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<decimal>("CopperN")
                        .HasPrecision(12, 6)
                        .HasColumnType("decimal(12,6)");

                    b.Property<int>("CopperUnit")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateLastModifiedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal>("DietaryFiber")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<decimal>("DietaryFiberN")
                        .HasPrecision(12, 6)
                        .HasColumnType("decimal(12,6)");

                    b.Property<int>("DietaryFiberUnit")
                        .HasColumnType("int");

                    b.Property<decimal>("Folate")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<decimal>("FolateN")
                        .HasPrecision(12, 6)
                        .HasColumnType("decimal(12,6)");

                    b.Property<int>("FolateUnit")
                        .HasColumnType("int");

                    b.Property<bool>("HasNutritionInfo")
                        .HasColumnType("bit");

                    b.Property<long>("HouseholdId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("InsolubleFiber")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<decimal>("InsolubleFiberN")
                        .HasPrecision(12, 6)
                        .HasColumnType("decimal(12,6)");

                    b.Property<int>("InsolubleFiberUnit")
                        .HasColumnType("int");

                    b.Property<decimal>("Iodine")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<decimal>("IodineN")
                        .HasPrecision(12, 6)
                        .HasColumnType("decimal(12,6)");

                    b.Property<int>("IodineUnit")
                        .HasColumnType("int");

                    b.Property<decimal>("Iron")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<decimal>("IronN")
                        .HasPrecision(12, 6)
                        .HasColumnType("decimal(12,6)");

                    b.Property<int>("IronUnit")
                        .HasColumnType("int");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPinned")
                        .HasColumnType("bit");

                    b.Property<decimal>("Magnesium")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<decimal>("MagnesiumN")
                        .HasPrecision(12, 6)
                        .HasColumnType("decimal(12,6)");

                    b.Property<int>("MagnesiumUnit")
                        .HasColumnType("int");

                    b.Property<decimal>("Manganese")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<decimal>("ManganeseN")
                        .HasPrecision(12, 6)
                        .HasColumnType("decimal(12,6)");

                    b.Property<int>("ManganeseUnit")
                        .HasColumnType("int");

                    b.Property<decimal>("Molybdenum")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<decimal>("MolybdenumN")
                        .HasPrecision(12, 6)
                        .HasColumnType("decimal(12,6)");

                    b.Property<int>("MolybdenumUnit")
                        .HasColumnType("int");

                    b.Property<decimal>("MonounsaturatedFat")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<decimal>("MonounsaturatedFatN")
                        .HasPrecision(12, 6)
                        .HasColumnType("decimal(12,6)");

                    b.Property<int>("MonounsaturatedFatUnit")
                        .HasColumnType("int");

                    b.Property<decimal>("Niacin")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<decimal>("NiacinN")
                        .HasPrecision(12, 6)
                        .HasColumnType("decimal(12,6)");

                    b.Property<int>("NiacinUnit")
                        .HasColumnType("int");

                    b.Property<decimal>("PantothenicAcid")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<decimal>("PantothenicAcidN")
                        .HasPrecision(12, 6)
                        .HasColumnType("decimal(12,6)");

                    b.Property<int>("PantothenicAcidUnit")
                        .HasColumnType("int");

                    b.Property<decimal>("Phosphorus")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<decimal>("PhosphorusN")
                        .HasPrecision(12, 6)
                        .HasColumnType("decimal(12,6)");

                    b.Property<int>("PhosphorusUnit")
                        .HasColumnType("int");

                    b.Property<decimal>("PolyunsaturatedFat")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<decimal>("PolyunsaturatedFatN")
                        .HasPrecision(12, 6)
                        .HasColumnType("decimal(12,6)");

                    b.Property<int>("PolyunsaturatedFatUnit")
                        .HasColumnType("int");

                    b.Property<decimal>("Potassium")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<decimal>("PotassiumN")
                        .HasPrecision(12, 6)
                        .HasColumnType("decimal(12,6)");

                    b.Property<int>("PotassiumUnit")
                        .HasColumnType("int");

                    b.Property<long?>("ProductCategoryId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Protein")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<decimal>("ProteinN")
                        .HasPrecision(12, 6)
                        .HasColumnType("decimal(12,6)");

                    b.Property<int>("ProteinUnit")
                        .HasColumnType("int");

                    b.Property<decimal>("Riboflavin")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<decimal>("RiboflavinN")
                        .HasPrecision(12, 6)
                        .HasColumnType("decimal(12,6)");

                    b.Property<int>("RiboflavinUnit")
                        .HasColumnType("int");

                    b.Property<decimal>("SaturatedFat")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<decimal>("SaturatedFatN")
                        .HasPrecision(12, 6)
                        .HasColumnType("decimal(12,6)");

                    b.Property<int>("SaturatedFatUnit")
                        .HasColumnType("int");

                    b.Property<decimal>("Selenium")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<decimal>("SeleniumN")
                        .HasPrecision(12, 6)
                        .HasColumnType("decimal(12,6)");

                    b.Property<int>("SeleniumUnit")
                        .HasColumnType("int");

                    b.Property<decimal>("ServingSize")
                        .HasPrecision(8, 3)
                        .HasColumnType("decimal(8,3)");

                    b.Property<decimal>("ServingSizeMetric")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<decimal>("ServingSizeMetricN")
                        .HasPrecision(12, 6)
                        .HasColumnType("decimal(12,6)");

                    b.Property<int>("ServingSizeMetricUnit")
                        .HasColumnType("int");

                    b.Property<decimal>("ServingSizeN")
                        .HasPrecision(13, 6)
                        .HasColumnType("decimal(13,6)");

                    b.Property<int>("ServingSizeUnit")
                        .HasColumnType("int");

                    b.Property<string>("ServingSizeUnitLabel")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<decimal>("ServingsPerContainer")
                        .HasPrecision(8, 3)
                        .HasColumnType("decimal(8,3)");

                    b.Property<decimal>("Sodium")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<decimal>("SodiumN")
                        .HasPrecision(12, 6)
                        .HasColumnType("decimal(12,6)");

                    b.Property<int>("SodiumUnit")
                        .HasColumnType("int");

                    b.Property<decimal>("SolubleFiber")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<decimal>("SolubleFiberN")
                        .HasPrecision(12, 6)
                        .HasColumnType("decimal(12,6)");

                    b.Property<int>("SolubleFiberUnit")
                        .HasColumnType("int");

                    b.Property<decimal>("SugarAlcohols")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<decimal>("SugarAlcoholsN")
                        .HasPrecision(12, 6)
                        .HasColumnType("decimal(12,6)");

                    b.Property<int>("SugarAlcoholsUnit")
                        .HasColumnType("int");

                    b.Property<decimal>("Thiamin")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<decimal>("ThiaminN")
                        .HasPrecision(12, 6)
                        .HasColumnType("decimal(12,6)");

                    b.Property<int>("ThiaminUnit")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal>("TotalCarbohydrates")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<decimal>("TotalCarbohydratesN")
                        .HasPrecision(12, 6)
                        .HasColumnType("decimal(12,6)");

                    b.Property<int>("TotalCarbohydratesUnit")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalFat")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<decimal>("TotalFatN")
                        .HasPrecision(12, 6)
                        .HasColumnType("decimal(12,6)");

                    b.Property<int>("TotalFatUnit")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalSugars")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<decimal>("TotalSugarsN")
                        .HasPrecision(12, 6)
                        .HasColumnType("decimal(12,6)");

                    b.Property<int>("TotalSugarsUnit")
                        .HasColumnType("int");

                    b.Property<decimal>("TransFat")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<decimal>("TransFatN")
                        .HasPrecision(12, 6)
                        .HasColumnType("decimal(12,6)");

                    b.Property<int>("TransFatUnit")
                        .HasColumnType("int");

                    b.Property<decimal>("VitaminA")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<decimal>("VitaminAN")
                        .HasPrecision(12, 6)
                        .HasColumnType("decimal(12,6)");

                    b.Property<int>("VitaminAUnit")
                        .HasColumnType("int");

                    b.Property<decimal>("VitaminB12")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<decimal>("VitaminB12N")
                        .HasPrecision(12, 6)
                        .HasColumnType("decimal(12,6)");

                    b.Property<int>("VitaminB12Unit")
                        .HasColumnType("int");

                    b.Property<decimal>("VitaminB6")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<decimal>("VitaminB6N")
                        .HasPrecision(12, 6)
                        .HasColumnType("decimal(12,6)");

                    b.Property<int>("VitaminB6Unit")
                        .HasColumnType("int");

                    b.Property<decimal>("VitaminC")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<decimal>("VitaminCN")
                        .HasPrecision(12, 6)
                        .HasColumnType("decimal(12,6)");

                    b.Property<int>("VitaminCUnit")
                        .HasColumnType("int");

                    b.Property<decimal>("VitaminD")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<decimal>("VitaminDN")
                        .HasPrecision(12, 6)
                        .HasColumnType("decimal(12,6)");

                    b.Property<int>("VitaminDUnit")
                        .HasColumnType("int");

                    b.Property<decimal>("VitaminE")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<decimal>("VitaminEN")
                        .HasPrecision(12, 6)
                        .HasColumnType("decimal(12,6)");

                    b.Property<int>("VitaminEUnit")
                        .HasColumnType("int");

                    b.Property<decimal>("VitaminK")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<decimal>("VitaminKN")
                        .HasPrecision(12, 6)
                        .HasColumnType("decimal(12,6)");

                    b.Property<int>("VitaminKUnit")
                        .HasColumnType("int");

                    b.Property<decimal>("Zinc")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<decimal>("ZincN")
                        .HasPrecision(12, 6)
                        .HasColumnType("decimal(12,6)");

                    b.Property<int>("ZincUnit")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DateCreatedUtc");

                    b.HasIndex("DateLastModifiedUtc");

                    b.HasIndex("HouseholdId");

                    b.HasIndex("ProductCategoryId");

                    b.HasIndex("HouseholdId", "Title");

                    b.ToTable("uk_Products", (string)null);
                });

            modelBuilder.Entity("Unshackled.Kitchen.Core.Data.Entities.ProductImageEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Container")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("DateCreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateLastModifiedUtc")
                        .HasColumnType("datetime2");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<long>("HouseholdId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("bit");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DateCreatedUtc");

                    b.HasIndex("DateLastModifiedUtc");

                    b.HasIndex("HouseholdId");

                    b.HasIndex("ProductId");

                    b.ToTable("uk_ProductImages", (string)null);
                });

            modelBuilder.Entity("Unshackled.Kitchen.Core.Data.Entities.ProductSubstitutionEntity", b =>
                {
                    b.Property<string>("IngredientKey")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint");

                    b.Property<long>("HouseholdId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit");

                    b.HasKey("IngredientKey", "ProductId");

                    b.HasIndex("ProductId");

                    b.HasIndex("HouseholdId", "IngredientKey");

                    b.ToTable("uk_ProductSubstitutions", (string)null);
                });

            modelBuilder.Entity("Unshackled.Kitchen.Core.Data.Entities.RecipeEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("CookTimeMinutes")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateLastModifiedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("HouseholdId")
                        .HasColumnType("bigint");

                    b.Property<int>("PrepTimeMinutes")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("TotalServings")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DateCreatedUtc");

                    b.HasIndex("DateLastModifiedUtc");

                    b.HasIndex("HouseholdId");

                    b.HasIndex("HouseholdId", "Title");

                    b.ToTable("uk_Recipes", (string)null);
                });

            modelBuilder.Entity("Unshackled.Kitchen.Core.Data.Entities.RecipeImageEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Container")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("DateCreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateLastModifiedUtc")
                        .HasColumnType("datetime2");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<long>("HouseholdId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("bit");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long>("RecipeId")
                        .HasColumnType("bigint");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DateCreatedUtc");

                    b.HasIndex("DateLastModifiedUtc");

                    b.HasIndex("HouseholdId");

                    b.HasIndex("RecipeId");

                    b.ToTable("uk_RecipeImages", (string)null);
                });

            modelBuilder.Entity("Unshackled.Kitchen.Core.Data.Entities.RecipeIngredientEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(8, 3)
                        .HasColumnType("decimal(8,3)");

                    b.Property<string>("AmountLabel")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<decimal>("AmountN")
                        .HasPrecision(15, 3)
                        .HasColumnType("decimal(15,3)");

                    b.Property<string>("AmountText")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int>("AmountUnit")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateLastModifiedUtc")
                        .HasColumnType("datetime2");

                    b.Property<long>("HouseholdId")
                        .HasColumnType("bigint");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long>("ListGroupId")
                        .HasColumnType("bigint");

                    b.Property<string>("PrepNote")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long>("RecipeId")
                        .HasColumnType("bigint");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("DateCreatedUtc");

                    b.HasIndex("DateLastModifiedUtc");

                    b.HasIndex("HouseholdId");

                    b.HasIndex("ListGroupId");

                    b.HasIndex("HouseholdId", "Key");

                    b.HasIndex("RecipeId", "SortOrder");

                    b.ToTable("uk_RecipeIngredients", (string)null);
                });

            modelBuilder.Entity("Unshackled.Kitchen.Core.Data.Entities.RecipeIngredientGroupEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DateCreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateLastModifiedUtc")
                        .HasColumnType("datetime2");

                    b.Property<long>("HouseholdId")
                        .HasColumnType("bigint");

                    b.Property<long>("RecipeId")
                        .HasColumnType("bigint");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DateCreatedUtc");

                    b.HasIndex("DateLastModifiedUtc");

                    b.HasIndex("HouseholdId");

                    b.HasIndex("RecipeId", "SortOrder");

                    b.ToTable("uk_RecipeIngredientGroups", (string)null);
                });

            modelBuilder.Entity("Unshackled.Kitchen.Core.Data.Entities.RecipeNoteEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DateCreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateLastModifiedUtc")
                        .HasColumnType("datetime2");

                    b.Property<long>("HouseholdId")
                        .HasColumnType("bigint");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("RecipeId")
                        .HasColumnType("bigint");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DateCreatedUtc");

                    b.HasIndex("DateLastModifiedUtc");

                    b.HasIndex("HouseholdId");

                    b.HasIndex("RecipeId", "SortOrder");

                    b.ToTable("uk_RecipeNotes", (string)null);
                });

            modelBuilder.Entity("Unshackled.Kitchen.Core.Data.Entities.RecipeStepEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DateCreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateLastModifiedUtc")
                        .HasColumnType("datetime2");

                    b.Property<long>("HouseholdId")
                        .HasColumnType("bigint");

                    b.Property<string>("Instructions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("RecipeId")
                        .HasColumnType("bigint");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DateCreatedUtc");

                    b.HasIndex("DateLastModifiedUtc");

                    b.HasIndex("HouseholdId");

                    b.HasIndex("RecipeId", "SortOrder");

                    b.ToTable("uk_RecipeSteps", (string)null);
                });

            modelBuilder.Entity("Unshackled.Kitchen.Core.Data.Entities.RecipeTagEntity", b =>
                {
                    b.Property<long>("RecipeId")
                        .HasColumnType("bigint");

                    b.Property<long>("TagId")
                        .HasColumnType("bigint");

                    b.HasKey("RecipeId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("uk_RecipeTags", (string)null);
                });

            modelBuilder.Entity("Unshackled.Kitchen.Core.Data.Entities.ShoppingListEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DateCreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateLastModifiedUtc")
                        .HasColumnType("datetime2");

                    b.Property<long>("HouseholdId")
                        .HasColumnType("bigint");

                    b.Property<long?>("StoreId")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("DateCreatedUtc");

                    b.HasIndex("DateLastModifiedUtc");

                    b.HasIndex("HouseholdId");

                    b.HasIndex("StoreId");

                    b.HasIndex("HouseholdId", "Title");

                    b.ToTable("uk_ShoppingLists", (string)null);
                });

            modelBuilder.Entity("Unshackled.Kitchen.Core.Data.Entities.ShoppingListItemEntity", b =>
                {
                    b.Property<long>("ShoppingListId")
                        .HasColumnType("bigint");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsInCart")
                        .HasColumnType("bit");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("ShoppingListId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("uk_ShoppingListItems", (string)null);
                });

            modelBuilder.Entity("Unshackled.Kitchen.Core.Data.Entities.ShoppingListRecipeItemEntity", b =>
                {
                    b.Property<long>("ShoppingListId")
                        .HasColumnType("bigint");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint");

                    b.Property<long>("RecipeId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("IngredientAmount")
                        .HasPrecision(8, 3)
                        .HasColumnType("decimal(8,3)");

                    b.Property<string>("IngredientAmountUnitLabel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IngredientAmountUnitType")
                        .HasColumnType("int");

                    b.Property<string>("IngredientKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsUnitMismatch")
                        .HasColumnType("bit");

                    b.Property<decimal>("PortionUsed")
                        .HasPrecision(15, 10)
                        .HasColumnType("decimal(15,10)");

                    b.Property<int>("ServingSizeUnitType")
                        .HasColumnType("int");

                    b.HasKey("ShoppingListId", "ProductId", "RecipeId");

                    b.HasIndex("ProductId");

                    b.HasIndex("RecipeId");

                    b.ToTable("uk_ShoppingListRecipeItems", (string)null);
                });

            modelBuilder.Entity("Unshackled.Kitchen.Core.Data.Entities.StoreEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DateCreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateLastModifiedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long>("HouseholdId")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("DateCreatedUtc");

                    b.HasIndex("DateLastModifiedUtc");

                    b.HasIndex("HouseholdId");

                    b.HasIndex("HouseholdId", "Title");

                    b.ToTable("uk_Stores", (string)null);
                });

            modelBuilder.Entity("Unshackled.Kitchen.Core.Data.Entities.StoreLocationEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DateCreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateLastModifiedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long>("HouseholdId")
                        .HasColumnType("bigint");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<long>("StoreId")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("DateCreatedUtc");

                    b.HasIndex("DateLastModifiedUtc");

                    b.HasIndex("HouseholdId");

                    b.HasIndex("StoreId");

                    b.HasIndex("HouseholdId", "StoreId", "SortOrder");

                    b.ToTable("uk_StoreLocations", (string)null);
                });

            modelBuilder.Entity("Unshackled.Kitchen.Core.Data.Entities.StoreProductLocationEntity", b =>
                {
                    b.Property<long>("StoreId")
                        .HasColumnType("bigint");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<long>("StoreLocationId")
                        .HasColumnType("bigint");

                    b.HasKey("StoreId", "ProductId");

                    b.HasIndex("ProductId");

                    b.HasIndex("StoreLocationId");

                    b.HasIndex("StoreId", "StoreLocationId", "SortOrder");

                    b.ToTable("uk_StoreProductLocations", (string)null);
                });

            modelBuilder.Entity("Unshackled.Kitchen.Core.Data.Entities.TagEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DateCreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateLastModifiedUtc")
                        .HasColumnType("datetime2");

                    b.Property<long>("HouseholdId")
                        .HasColumnType("bigint");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("DateCreatedUtc");

                    b.HasIndex("DateLastModifiedUtc");

                    b.HasIndex("HouseholdId");

                    b.HasIndex("Title");

                    b.HasIndex("HouseholdId", "Key")
                        .IsUnique();

                    b.ToTable("uk_Tags", (string)null);
                });

            modelBuilder.Entity("Unshackled.Studio.Core.Data.Entities.MemberEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("AppTheme")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateLastModifiedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("DateCreatedUtc");

                    b.HasIndex("DateLastModifiedUtc");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("uk_Members", (string)null);
                });

            modelBuilder.Entity("Unshackled.Studio.Core.Data.Entities.MemberMetaEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("MemberId")
                        .HasMaxLength(450)
                        .HasColumnType("bigint");

                    b.Property<string>("MetaKey")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("MetaValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MemberId", "MetaKey")
                        .IsUnique();

                    b.ToTable("uk_MemberMeta", (string)null);
                });

            modelBuilder.Entity("Unshackled.Studio.Core.Data.Entities.UserEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("uk_Users", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Unshackled.Studio.Core.Data.Entities.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Unshackled.Studio.Core.Data.Entities.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Unshackled.Studio.Core.Data.Entities.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Unshackled.Studio.Core.Data.Entities.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Unshackled.Kitchen.Core.Data.Entities.CookbookEntity", b =>
                {
                    b.HasOne("Unshackled.Studio.Core.Data.Entities.MemberEntity", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("Unshackled.Kitchen.Core.Data.Entities.CookbookInviteEntity", b =>
                {
                    b.HasOne("Unshackled.Kitchen.Core.Data.Entities.CookbookEntity", "Cookbook")
                        .WithMany("Invites")
                        .HasForeignKey("CookbookId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Cookbook");
                });

            modelBuilder.Entity("Unshackled.Kitchen.Core.Data.Entities.CookbookMemberEntity", b =>
                {
                    b.HasOne("Unshackled.Kitchen.Core.Data.Entities.CookbookEntity", "Cookbook")
                        .WithMany("Memberships")
                        .HasForeignKey("CookbookId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Unshackled.Studio.Core.Data.Entities.MemberEntity", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Cookbook");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("Unshackled.Kitchen.Core.Data.Entities.CookbookRecipeEntity", b =>
                {
                    b.HasOne("Unshackled.Kitchen.Core.Data.Entities.CookbookEntity", "Cookbook")
                        .WithMany()
                        .HasForeignKey("CookbookId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Unshackled.Kitchen.Core.Data.Entities.HouseholdEntity", "Household")
                        .WithMany()
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Unshackled.Studio.Core.Data.Entities.MemberEntity", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Unshackled.Kitchen.Core.Data.Entities.RecipeEntity", "Recipe")
                        .WithMany()
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Cookbook");

                    b.Navigation("Household");

                    b.Navigation("Member");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("Unshackled.Kitchen.Core.Data.Entities.HouseholdEntity", b =>
                {
                    b.HasOne("Unshackled.Studio.Core.Data.Entities.MemberEntity", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("Unshackled.Kitchen.Core.Data.Entities.HouseholdInviteEntity", b =>
                {
                    b.HasOne("Unshackled.Kitchen.Core.Data.Entities.HouseholdEntity", "Household")
                        .WithMany("Invites")
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Household");
                });

            modelBuilder.Entity("Unshackled.Kitchen.Core.Data.Entities.HouseholdMemberEntity", b =>
                {
                    b.HasOne("Unshackled.Kitchen.Core.Data.Entities.HouseholdEntity", "Household")
                        .WithMany("Memberships")
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Unshackled.Studio.Core.Data.Entities.MemberEntity", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Household");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("Unshackled.Kitchen.Core.Data.Entities.MealDefinitionEntity", b =>
                {
                    b.HasOne("Unshackled.Kitchen.Core.Data.Entities.HouseholdEntity", "Household")
                        .WithMany()
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Household");
                });

            modelBuilder.Entity("Unshackled.Kitchen.Core.Data.Entities.MealPlanRecipeEntity", b =>
                {
                    b.HasOne("Unshackled.Kitchen.Core.Data.Entities.HouseholdEntity", "Household")
                        .WithMany()
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Unshackled.Kitchen.Core.Data.Entities.MealDefinitionEntity", "MealDefinition")
                        .WithMany()
                        .HasForeignKey("MealDefinitionId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Unshackled.Kitchen.Core.Data.Entities.RecipeEntity", "Recipe")
                        .WithMany()
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Household");

                    b.Navigation("MealDefinition");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("Unshackled.Kitchen.Core.Data.Entities.ProductBundleEntity", b =>
                {
                    b.HasOne("Unshackled.Kitchen.Core.Data.Entities.HouseholdEntity", "Household")
                        .WithMany()
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Household");
                });

            modelBuilder.Entity("Unshackled.Kitchen.Core.Data.Entities.ProductBundleItemEntity", b =>
                {
                    b.HasOne("Unshackled.Kitchen.Core.Data.Entities.ProductBundleEntity", "ProductBundle")
                        .WithMany("Products")
                        .HasForeignKey("ProductBundleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Unshackled.Kitchen.Core.Data.Entities.ProductEntity", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("ProductBundle");
                });

            modelBuilder.Entity("Unshackled.Kitchen.Core.Data.Entities.ProductCategoryEntity", b =>
                {
                    b.HasOne("Unshackled.Kitchen.Core.Data.Entities.HouseholdEntity", "Household")
                        .WithMany()
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Household");
                });

            modelBuilder.Entity("Unshackled.Kitchen.Core.Data.Entities.ProductEntity", b =>
                {
                    b.HasOne("Unshackled.Kitchen.Core.Data.Entities.HouseholdEntity", "Household")
                        .WithMany()
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Unshackled.Kitchen.Core.Data.Entities.ProductCategoryEntity", "Category")
                        .WithMany("Products")
                        .HasForeignKey("ProductCategoryId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Category");

                    b.Navigation("Household");
                });

            modelBuilder.Entity("Unshackled.Kitchen.Core.Data.Entities.ProductImageEntity", b =>
                {
                    b.HasOne("Unshackled.Kitchen.Core.Data.Entities.HouseholdEntity", "Household")
                        .WithMany()
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Unshackled.Kitchen.Core.Data.Entities.ProductEntity", "Product")
                        .WithMany("Images")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Household");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Unshackled.Kitchen.Core.Data.Entities.ProductSubstitutionEntity", b =>
                {
                    b.HasOne("Unshackled.Kitchen.Core.Data.Entities.HouseholdEntity", "Household")
                        .WithMany()
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Unshackled.Kitchen.Core.Data.Entities.ProductEntity", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Household");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Unshackled.Kitchen.Core.Data.Entities.RecipeEntity", b =>
                {
                    b.HasOne("Unshackled.Kitchen.Core.Data.Entities.HouseholdEntity", "Household")
                        .WithMany()
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Household");
                });

            modelBuilder.Entity("Unshackled.Kitchen.Core.Data.Entities.RecipeImageEntity", b =>
                {
                    b.HasOne("Unshackled.Kitchen.Core.Data.Entities.HouseholdEntity", "Household")
                        .WithMany()
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Unshackled.Kitchen.Core.Data.Entities.RecipeEntity", "Recipe")
                        .WithMany("Images")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Household");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("Unshackled.Kitchen.Core.Data.Entities.RecipeIngredientEntity", b =>
                {
                    b.HasOne("Unshackled.Kitchen.Core.Data.Entities.HouseholdEntity", "Household")
                        .WithMany()
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Unshackled.Kitchen.Core.Data.Entities.RecipeIngredientGroupEntity", "ListGroup")
                        .WithMany("Ingredients")
                        .HasForeignKey("ListGroupId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Unshackled.Kitchen.Core.Data.Entities.RecipeEntity", "Recipe")
                        .WithMany("Ingredients")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Household");

                    b.Navigation("ListGroup");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("Unshackled.Kitchen.Core.Data.Entities.RecipeIngredientGroupEntity", b =>
                {
                    b.HasOne("Unshackled.Kitchen.Core.Data.Entities.HouseholdEntity", "Household")
                        .WithMany()
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Unshackled.Kitchen.Core.Data.Entities.RecipeEntity", "Recipe")
                        .WithMany("Groups")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Household");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("Unshackled.Kitchen.Core.Data.Entities.RecipeNoteEntity", b =>
                {
                    b.HasOne("Unshackled.Kitchen.Core.Data.Entities.HouseholdEntity", "Household")
                        .WithMany()
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Unshackled.Kitchen.Core.Data.Entities.RecipeEntity", "Recipe")
                        .WithMany("Notes")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Household");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("Unshackled.Kitchen.Core.Data.Entities.RecipeStepEntity", b =>
                {
                    b.HasOne("Unshackled.Kitchen.Core.Data.Entities.HouseholdEntity", "Household")
                        .WithMany()
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Unshackled.Kitchen.Core.Data.Entities.RecipeEntity", "Recipe")
                        .WithMany("Steps")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Household");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("Unshackled.Kitchen.Core.Data.Entities.RecipeTagEntity", b =>
                {
                    b.HasOne("Unshackled.Kitchen.Core.Data.Entities.RecipeEntity", "Recipe")
                        .WithMany()
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Unshackled.Kitchen.Core.Data.Entities.TagEntity", "Tag")
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Recipe");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("Unshackled.Kitchen.Core.Data.Entities.ShoppingListEntity", b =>
                {
                    b.HasOne("Unshackled.Kitchen.Core.Data.Entities.HouseholdEntity", "Household")
                        .WithMany()
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Unshackled.Kitchen.Core.Data.Entities.StoreEntity", "Store")
                        .WithMany()
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Household");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("Unshackled.Kitchen.Core.Data.Entities.ShoppingListItemEntity", b =>
                {
                    b.HasOne("Unshackled.Kitchen.Core.Data.Entities.ProductEntity", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Unshackled.Kitchen.Core.Data.Entities.ShoppingListEntity", "ShoppingList")
                        .WithMany("Items")
                        .HasForeignKey("ShoppingListId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("ShoppingList");
                });

            modelBuilder.Entity("Unshackled.Kitchen.Core.Data.Entities.ShoppingListRecipeItemEntity", b =>
                {
                    b.HasOne("Unshackled.Kitchen.Core.Data.Entities.ProductEntity", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Unshackled.Kitchen.Core.Data.Entities.RecipeEntity", "Recipe")
                        .WithMany()
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Unshackled.Kitchen.Core.Data.Entities.ShoppingListEntity", "ShoppingList")
                        .WithMany("RecipeItems")
                        .HasForeignKey("ShoppingListId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Recipe");

                    b.Navigation("ShoppingList");
                });

            modelBuilder.Entity("Unshackled.Kitchen.Core.Data.Entities.StoreEntity", b =>
                {
                    b.HasOne("Unshackled.Kitchen.Core.Data.Entities.HouseholdEntity", "Household")
                        .WithMany()
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Household");
                });

            modelBuilder.Entity("Unshackled.Kitchen.Core.Data.Entities.StoreLocationEntity", b =>
                {
                    b.HasOne("Unshackled.Kitchen.Core.Data.Entities.HouseholdEntity", "Household")
                        .WithMany()
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Unshackled.Kitchen.Core.Data.Entities.StoreEntity", "Store")
                        .WithMany("Locations")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Household");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("Unshackled.Kitchen.Core.Data.Entities.StoreProductLocationEntity", b =>
                {
                    b.HasOne("Unshackled.Kitchen.Core.Data.Entities.ProductEntity", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Unshackled.Kitchen.Core.Data.Entities.StoreEntity", "Store")
                        .WithMany()
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Unshackled.Kitchen.Core.Data.Entities.StoreLocationEntity", "StoreLocation")
                        .WithMany()
                        .HasForeignKey("StoreLocationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Store");

                    b.Navigation("StoreLocation");
                });

            modelBuilder.Entity("Unshackled.Kitchen.Core.Data.Entities.TagEntity", b =>
                {
                    b.HasOne("Unshackled.Kitchen.Core.Data.Entities.HouseholdEntity", "Household")
                        .WithMany()
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Household");
                });

            modelBuilder.Entity("Unshackled.Studio.Core.Data.Entities.MemberMetaEntity", b =>
                {
                    b.HasOne("Unshackled.Studio.Core.Data.Entities.MemberEntity", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("Unshackled.Kitchen.Core.Data.Entities.CookbookEntity", b =>
                {
                    b.Navigation("Invites");

                    b.Navigation("Memberships");
                });

            modelBuilder.Entity("Unshackled.Kitchen.Core.Data.Entities.HouseholdEntity", b =>
                {
                    b.Navigation("Invites");

                    b.Navigation("Memberships");
                });

            modelBuilder.Entity("Unshackled.Kitchen.Core.Data.Entities.ProductBundleEntity", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Unshackled.Kitchen.Core.Data.Entities.ProductCategoryEntity", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Unshackled.Kitchen.Core.Data.Entities.ProductEntity", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("Unshackled.Kitchen.Core.Data.Entities.RecipeEntity", b =>
                {
                    b.Navigation("Groups");

                    b.Navigation("Images");

                    b.Navigation("Ingredients");

                    b.Navigation("Notes");

                    b.Navigation("Steps");
                });

            modelBuilder.Entity("Unshackled.Kitchen.Core.Data.Entities.RecipeIngredientGroupEntity", b =>
                {
                    b.Navigation("Ingredients");
                });

            modelBuilder.Entity("Unshackled.Kitchen.Core.Data.Entities.ShoppingListEntity", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("RecipeItems");
                });

            modelBuilder.Entity("Unshackled.Kitchen.Core.Data.Entities.StoreEntity", b =>
                {
                    b.Navigation("Locations");
                });
#pragma warning restore 612, 618
        }
    }
}
