using Unshackled.Food.Core.Enums;

namespace Unshackled.Food.Core.Models.Recipes;

public interface INutrition
{
	bool HasNutritionInfo { get; set; }
	decimal ServingSize { get; set; }
	ServingSizeUnits ServingSizeUnit { get; set; }
	string ServingSizeUnitLabel { get; set; }
	decimal ServingSizeMetric { get; set; }
	ServingSizeMetricUnits ServingSizeMetricUnit { get; set; }
	decimal ServingsPerContainer { get; set; }
	int Calories { get; set; }
	int CaloriesFromFat { get; set; }
	decimal TotalFat { get; set; }
	NutritionUnits TotalFatUnit { get; set; }
	decimal SaturatedFat { get; set; }
	NutritionUnits SaturatedFatUnit { get; set; }
	decimal TransFat { get; set; }
	NutritionUnits TransFatUnit { get; set; }
	decimal PolyunsaturatedFat { get; set; }
	NutritionUnits PolyunsaturatedFatUnit { get; set; }
	decimal MonounsaturatedFat { get; set; }
	NutritionUnits MonounsaturatedFatUnit { get; set; }
	decimal Cholesterol { get; set; }
	NutritionUnits CholesterolUnit { get; set; }
	decimal TotalCarbohydrates { get; set; }
	NutritionUnits TotalCarbohydratesUnit { get; set; }
	decimal DietaryFiber { get; set; }
	NutritionUnits DietaryFiberUnit { get; set; }
	decimal SolubleFiber { get; set; }
	NutritionUnits SolubleFiberUnit { get; set; }
	decimal InsolubleFiber { get; set; }
	NutritionUnits InsolubleFiberUnit { get; set; }
	decimal TotalSugars { get; set; }
	NutritionUnits TotalSugarsUnit { get; set; }
	decimal AddedSugars { get; set; }
	NutritionUnits AddedSugarsUnit { get; set; }
	decimal SugarAlcohols { get; set; }
	NutritionUnits SugarAlcoholsUnit { get; set; }
	decimal Protein { get; set; }
	NutritionUnits ProteinUnit { get; set; }
	decimal Biotin { get; set; }
	NutritionUnits BiotinUnit { get; set; }
	decimal Choline { get; set; }
	NutritionUnits CholineUnit { get; set; }
	decimal Folate { get; set; }
	NutritionUnits FolateUnit { get; set; }
	decimal Niacin { get; set; }
	NutritionUnits NiacinUnit { get; set; }
	decimal PantothenicAcid { get; set; }
	NutritionUnits PantothenicAcidUnit { get; set; }
	decimal Riboflavin { get; set; }
	NutritionUnits RiboflavinUnit { get; set; }
	decimal Thiamin { get; set; }
	NutritionUnits ThiaminUnit { get; set; }
	decimal VitaminA { get; set; }
	NutritionUnits VitaminAUnit { get; set; }
	decimal VitaminB6 { get; set; }
	NutritionUnits VitaminB6Unit { get; set; }
	decimal VitaminB12 { get; set; }
	NutritionUnits VitaminB12Unit { get; set; }
	decimal VitaminC { get; set; }
	NutritionUnits VitaminCUnit { get; set; }
	decimal VitaminD { get; set; }
	NutritionUnits VitaminDUnit { get; set; }
	decimal VitaminE { get; set; }
	NutritionUnits VitaminEUnit { get; set; }
	decimal VitaminK { get; set; }
	NutritionUnits VitaminKUnit { get; set; }
	decimal Calcium { get; set; }
	NutritionUnits CalciumUnit { get; set; }
	decimal Chloride { get; set; }
	NutritionUnits ChlorideUnit { get; set; }
	decimal Chromium { get; set; }
	NutritionUnits ChromiumUnit { get; set; }
	decimal Copper { get; set; }
	NutritionUnits CopperUnit { get; set; }
	decimal Iodine { get; set; }
	NutritionUnits IodineUnit { get; set; }
	decimal Iron { get; set; }
	NutritionUnits IronUnit { get; set; }
	decimal Magnesium { get; set; }
	NutritionUnits MagnesiumUnit { get; set; }
	decimal Manganese { get; set; }
	NutritionUnits ManganeseUnit { get; set; }
	decimal Molybdenum { get; set; }
	NutritionUnits MolybdenumUnit { get; set; }
	decimal Phosphorus { get; set; }
	NutritionUnits PhosphorusUnit { get; set; }
	decimal Potassium { get; set; }
	NutritionUnits PotassiumUnit { get; set; }
	decimal Selenium { get; set; }
	NutritionUnits SeleniumUnit { get; set; }
	decimal Sodium { get; set; }
	NutritionUnits SodiumUnit { get; set; }
	decimal Zinc { get; set; }
	NutritionUnits ZincUnit { get; set; }
}
