namespace Unshackled.Food.Core.Enums;

public enum CuisineTypes
{
	Any,
	Australian,
	CajunCreole,
	Caribbean,
	CentralAfrican,
	CentralAmerican,
	CentralAsian,
	CentralEuropean,
	Chinese,
	EastAfrican,
	EastAsian,
	EasternEuropean,
	Filipino,
	German,
	Greek,
	French,
	Fusion,
	Indian,
	Indonesian,
	Italian,
	Japanese,
	Korean,
	Mexican,
	NativeAmerican,
	NorthAfrican,
	NorthAmerican,
	NorthernEuropean,
	Oceanic,
	Pakistani,
	Polish,
	Polynesian,
	Russian,
	SoulFood,
	SouthAfrican,
	SouthAmerican,
	SouthAsian,
	SoutheastAsian,
	SouthernEuropean,
	Spanish,
	TexMex,
	Thai,
	WestAfrican,
	WestAsian,
	WesternEuropean,
	Vietnamese
}

public static class CuisineTypesExtensions
{
	public static string Title(this CuisineTypes cuisine) => cuisine switch
	{
		CuisineTypes.Any => "All",
		CuisineTypes.Australian => "Australian",
		CuisineTypes.CajunCreole => "Cajun and Creole",
		CuisineTypes.Caribbean => "Caribbean",
		CuisineTypes.CentralAfrican => "Central African",
		CuisineTypes.CentralAmerican => "Central American",
		CuisineTypes.CentralAsian => "Central Asian",
		CuisineTypes.CentralEuropean => "Central European",
		CuisineTypes.Chinese => "Chinese",
		CuisineTypes.EastAfrican => "East African",
		CuisineTypes.EastAsian => "East Asian",
		CuisineTypes.EasternEuropean => "East European",
		CuisineTypes.Filipino => "Filipino",
		CuisineTypes.German => "German",
		CuisineTypes.Greek => "Greek",
		CuisineTypes.French => "French",
		CuisineTypes.Fusion => "Fusion",
		CuisineTypes.Indian => "Indian",
		CuisineTypes.Indonesian => "Indonesian",
		CuisineTypes.Italian => "Italian",
		CuisineTypes.Japanese => "Japanese",
		CuisineTypes.Korean => "Korean",
		CuisineTypes.Mexican => "Mexican",
		CuisineTypes.NativeAmerican => "Native American",
		CuisineTypes.NorthAfrican => "North African",
		CuisineTypes.NorthAmerican => "North American",
		CuisineTypes.NorthernEuropean => "Northern European",
		CuisineTypes.Oceanic => "Oceanic",
		CuisineTypes.Pakistani => "Pakistani",
		CuisineTypes.Polish => "Polish",
		CuisineTypes.Polynesian => "Polynesian",
		CuisineTypes.Russian => "Russian",
		CuisineTypes.SoulFood => "Soul Food",
		CuisineTypes.SouthAfrican => "South African",
		CuisineTypes.SouthAmerican => "South American",
		CuisineTypes.SouthAsian => "South Asian",
		CuisineTypes.SoutheastAsian => "Southeast Asian",
		CuisineTypes.SouthernEuropean => "Southern European",
		CuisineTypes.Spanish => "Spanish",
		CuisineTypes.TexMex => "Tex-Mex",
		CuisineTypes.Thai => "Thai",
		CuisineTypes.WestAfrican => "West African",
		CuisineTypes.WestAsian => "West Asian",
		CuisineTypes.WesternEuropean => "Western European",
		CuisineTypes.Vietnamese => "Vietnamese",
		_ => string.Empty,
	};
}
